=== RuchiAgrawal9186/practice/100DaysLearning/Day_23_XML/employee.xsd
<!-- rules or validation for xml -->

<xs:schema xmlns:xs="https://www.example.com/2025/XMLSchemas">
<xs:element name="employees">
<xs:complexType>
<xs:element name="employee">
<xs:complexType>
<xs:sequence>
<xs:element name="name" type="xs:string"></xs:element>
<xs:element name="age" type="xs:integer"></xs:element>
<xs:element name="email" type="xs:string"></xs:element>
<xs:element name="gender" type="xs:string"></xs:element>
<xs:element name="phone" type="xs:integer"></xs:element>
<xs:element name="cityAddress" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:complexType>
</xs:element>
</xs:schema>

=== RuchiAgrawal9186/practice/100DaysLearning/Day_23_XML/employee.xml
<employees xmlns="https://www.example.com/employee" xmlns:xsl="https://www.example.com/2025/XMLSchemas" xsi:schemaLocation="https://www.example.com/employee employee.xsd">
    <employee status="active">
    <name>ABC</name>
    <age>20</age>
    <email>abc@gmail.com</email>
    <gender>Male</gender>
    <phone>1234567890</phone>
    <cityAddress>Ahemadabad</cityAddress>
    </employee>

    <employee status="Inactive">
    <name>xyz</name>
    <age>30</age>
    <email>xyz@gmail.com</email>
    <gender>Male</gender>
    <phone>0123456789</phone>
    <cityAddress>Baroda</cityAddress>
    </employee>
</employees>
